// Authentic Mock Tamil Matrimony Profiles Data for Jothi Matrimony

export const MOCK_PROFILES = [
  {
    id: "JM202600101",
    name: "Priya Sundaram",
    gender: "Female",
    age: 27,
    dob: "1999-05-14",
    birthTime: "08:15 AM",
    birthPlace: "Chennai",
    height: "5' 5\" (165 cm)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Iyer",
    subcaste: "Vadama",
    gothram: "Kashyapa",
    education: "M.S. Software Engineering",
    institution: "College of Engineering, Guindy (CEG)",
    profession: "Senior Software Engineer",
    company: "Amazon India",
    annualIncome: "₹24,000,000 / annum",
    city: "Chennai",
    nativeTown: "Kanchipuram",
    state: "Tamil Nadu",
    country: "India",
    
    // Horoscope details
    rasi: "Simmam (Leo)",
    nakshatra: "Magam",
    padam: "2",
    lagnam: "Kanni (Virgo)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Meenam"],
      2: ["Mesham", "Guru"],
      3: ["Rishabam", "Rahu"],
      4: ["Mithunam"],
      5: ["Katakamd"],
      6: ["Simmam", "Chandran"], // Moon in Simmam
      7: ["Kanni", "Lagnam"], // Lagna in Kanni
      8: ["Thulaam", "Sukran", "Budhan"],
      9: ["Vrichigam", "Suriyan"],
      10: ["Dhanusu", "Sevvai"],
      11: ["Makaram", "Sani"],
      12: ["Kumbam", "Kethu"]
    },
    
    // Family Details
    family: {
      fatherName: "S. Sundaram",
      fatherOccupation: "Retired General Manager, Indian Overseas Bank",
      motherName: "Lakshmi Sundaram",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Brother (B.Tech, Working in Bengaluru)",
      familyType: "Nuclear Family",
      familyValues: "Traditional & Modern",
      familyStatus: "Upper Middle Class",
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 27,
      ageMax: 32,
      heightMin: "5' 8\"",
      maritalStatus: "Never Married",
      education: "Master's / B.Tech / M.Tech / MBA",
      profession: "IT Professional / Doctor / Civil Services / Executive",
      location: "Chennai / Bengaluru / USA / Singapore",
      castePreference: "Same / Open to Subcaste",
      horoscopeMatchReq: "Mandatory (Minimum 7 Poruthams)"
    },
    
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600",
    gallery: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600"
    ],
    about: "Warm, empathetic and ambitious software developer based in Chennai. I respect traditional Tamil values while retaining a modern independent outlook. Enjoys Carnatic music, filter coffee, reading books and weekend travels with family.",
    phone: "+91 98401 23456",
    email: "priya.sundaram.jm@gmail.com",
    verified: true,
    joinedDate: "2026-01-10"
  },
  {
    id: "JM202600102",
    name: "Karthik Raja",
    gender: "Male",
    age: 29,
    dob: "1997-08-22",
    birthTime: "06:45 PM",
    birthPlace: "Coimbatore",
    height: "5' 11\" (180 cm)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Gounder",
    subcaste: "Kongu Vellalar",
    gothram: "Sengunthar",
    education: "B.E. Mechanical Engineering, MBA",
    institution: "PSG Tech, Coimbatore",
    profession: "Product Manager",
    company: "Zoho Corporation",
    annualIncome: "₹28,000,000 / annum",
    city: "Chennai",
    nativeTown: "Pollachi",
    state: "Tamil Nadu",
    country: "India",
    
    rasi: "Rishabam (Taurus)",
    nakshatra: "Rohini",
    padam: "3",
    lagnam: "Mesham (Aries)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Mesham", "Lagnam", "Suriyan"],
      2: ["Rishabam", "Chandran"],
      3: ["Mithunam", "Budhan"],
      4: ["Katakamd", "Sukran"],
      5: ["Simmam"],
      6: ["Kanni", "Rahu"],
      7: ["Thulaam"],
      8: ["Vrichigam", "Guru"],
      9: ["Dhanusu"],
      10: ["Makaram", "Sani"],
      11: ["Kumbam", "Sevvai"],
      12: ["Meenam", "Kethu"]
    },
    
    family: {
      fatherName: "K. Rajendran",
      fatherOccupation: "Agriculturalist & Textile Business Owner",
      motherName: "Visalakshi Rajendran",
      motherOccupation: "Homemaker",
      siblings: "1 Elder Sister (Married, Settled in USA)",
      familyType: "Joint Family",
      familyValues: "Traditional",
      familyStatus: "Affluent / Wealthy",
    },
    
    partnerPreferences: {
      ageMin: 24,
      ageMax: 28,
      heightMin: "5' 3\"",
      maritalStatus: "Never Married",
      education: "Bachelor's or Master's Degree",
      profession: "Software / Healthcare / Teaching / Finance",
      location: "Tamil Nadu / Bengaluru",
      castePreference: "Kongu Vellalar Gounder / Open",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
    gallery: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600"
    ],
    about: "Tech-savvy product manager with deep roots in Kongu Nadu culture. Passionate about innovation, organic farming, playing badminton, and Tamil literature. Looking for an understanding, educated soul to share life's journey.",
    phone: "+91 94432 87654",
    email: "karthik.raja.jm@gmail.com",
    verified: true,
    joinedDate: "2026-02-01"
  },
  {
    id: "JM202600103",
    name: "Dr. Anitha Ramachandran",
    gender: "Female",
    age: 28,
    dob: "1998-03-19",
    birthTime: "11:20 AM",
    birthPlace: "Madurai",
    height: "5' 6\" (168 cm)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Pillai",
    subcaste: "Saiva Pillai",
    gothram: "Siva",
    education: "M.D. Pediatrics",
    institution: "Madurai Medical College",
    profession: "Consultant Pediatrician",
    company: "Apollo Children's Hospital",
    annualIncome: "₹18,000,000 / annum",
    city: "Chennai",
    nativeTown: "Madurai",
    state: "Tamil Nadu",
    country: "India",
    
    rasi: "Thulaam (Libra)",
    nakshatra: "Swathi",
    padam: "1",
    lagnam: "Dhanusu (Sagittarius)",
    chevvaiDosham: "Yes (Mild)",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Dhanusu", "Lagnam"],
      2: ["Makaram"],
      3: ["Kumbam"],
      4: ["Meenam", "Guru"],
      5: ["Mesham"],
      6: ["Rishabam", "Rahu"],
      7: ["Mithunam"],
      8: ["Katakamd", "Sevvai"],
      9: ["Simmam"],
      10: ["Kanni", "Suriyan", "Budhan"],
      11: ["Thulaam", "Chandran", "Sukran"],
      12: ["Vrichigam", "Sani", "Kethu"]
    },
    
    family: {
      fatherName: "Dr. M. Ramachandran",
      fatherOccupation: "Chief Civil Surgeon (Retd)",
      motherName: "Saraswathi Ramachandran",
      motherOccupation: "School Principal (Retd)",
      siblings: "None (Single Child)",
      familyType: "Nuclear Family",
      familyValues: "Traditional & Cultural",
      familyStatus: "Upper Middle Class",
    },
    
    partnerPreferences: {
      ageMin: 28,
      ageMax: 33,
      heightMin: "5' 8\"",
      maritalStatus: "Never Married",
      education: "M.D. / M.S. / M.Ch / IAS / IPS / Tech Exec",
      profession: "Doctor / Healthcare / Civil Services / IT Professional",
      location: "Chennai / Madurai / Coimbatore",
      castePreference: "Saiva Pillai / Vellalar / Open to All Hindu",
      horoscopeMatchReq: "Mandatory (Chevvai match preferred)"
    },
    
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600",
    gallery: [
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600"
    ],
    about: "Dedicated pediatrician with a compassionate heart. Dedicated to child healthcare and medical research. Enjoys Bharatanatyam, classical music concerts at Narada Gana Sabha, and family gatherings.",
    phone: "+91 99940 11223",
    email: "anitha.ram.md@gmail.com",
    verified: true,
    joinedDate: "2026-02-14"
  },
  {
    id: "JM202600104",
    name: "Vignesh Murugan",
    gender: "Male",
    age: 31,
    dob: "1995-11-05",
    birthTime: "04:30 AM",
    birthPlace: "Trichy",
    height: "5' 10\" (178 cm)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Chettiar",
    subcaste: "Nattukottai Nagarathar",
    gothram: "Kazh anivaasarkovil",
    education: "Chartered Accountant (FCA), B.Com",
    institution: "ICA, Chennai",
    profession: "VP Finance & Taxation",
    company: "TVS Motor Company",
    annualIncome: "₹35,000,000 / annum",
    city: "Chennai",
    nativeTown: "Devakottai, Chettinad",
    state: "Tamil Nadu",
    country: "India",
    
    rasi: "Kanni (Virgo)",
    nakshatra: "Uthiram",
    padam: "4",
    lagnam: "Simmam (Leo)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Simmam", "Lagnam", "Suriyan"],
      2: ["Kanni", "Chandran", "Budhan"],
      3: ["Thulaam"],
      4: ["Vrichigam", "Sukran"],
      5: ["Dhanusu", "Guru"],
      6: ["Makaram", "Sani"],
      7: ["Kumbam", "Rahu"],
      8: ["Meenam"],
      9: ["Mesham"],
      10: ["Rishabam", "Sevvai"],
      11: ["Mithunam"],
      12: ["Katakamd", "Kethu"]
    },
    
    family: {
      fatherName: "AL. Murugappan",
      fatherOccupation: "Industrialist & Bank Board Director",
      motherName: "Meenal Murugappan",
      motherOccupation: "Homemaker",
      siblings: "2 Elder Brothers (Both Married & Running Family Business)",
      familyType: "Joint Family",
      familyValues: "Traditional Nagarathar Culture",
      familyStatus: "Affluent / High Net Worth",
    },
    
    partnerPreferences: {
      ageMin: 25,
      ageMax: 29,
      heightMin: "5' 4\"",
      maritalStatus: "Never Married",
      education: "CA / MBA / B.Tech / M.Com",
      profession: "Finance / IT / Corporate / Family Business / Architect",
      location: "Chennai / Chettinad / Singapore / UAE",
      castePreference: "Nagarathar Chettiar preferred",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600",
    gallery: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600"
    ],
    about: "Senior finance professional hailing from Chettinad heritage. Loves financial strategy, architecture, Chettinad cuisine, and temple architecture restoration projects. Seeking a culturally grounded, cheerful partner.",
    phone: "+91 98410 99887",
    email: "vignesh.nagarathar@gmail.com",
    verified: true,
    joinedDate: "2026-01-28"
  },
  {
    id: "JM202600105",
    name: "Divya Natesan",
    gender: "Female",
    age: 26,
    dob: "2000-01-29",
    birthTime: "10:00 AM",
    birthPlace: "Salem",
    height: "5' 4\" (163 cm)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Mudaliar",
    subcaste: "Thondaimandala Saiva Mudaliar",
    gothram: "Siva",
    education: "B.Arch (Architecture)",
    institution: "Anna University School of Architecture",
    profession: "Senior Interior Architect",
    company: "SpaceMatrix Design Studio",
    annualIncome: "₹15,000,000 / annum",
    city: "Chennai",
    nativeTown: "Salem",
    state: "Tamil Nadu",
    country: "India",
    
    rasi: "Dhanusu (Sagittarius)",
    nakshatra: "Moolam",
    padam: "1",
    lagnam: "Meenam (Pisces)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Meenam", "Lagnam"],
      2: ["Mesham"],
      3: ["Rishabam", "Sani"],
      4: ["Mithunam", "Rahu"],
      5: ["Katakamd"],
      6: ["Simmam"],
      7: ["Kanni", "Sevvai"],
      8: ["Thulaam"],
      9: ["Vrichigam"],
      10: ["Dhanusu", "Chandran", "Guru"],
      11: ["Makaram", "Suriyan", "Budhan"],
      12: ["Kumbam", "Sukran", "Kethu"]
    },
    
    family: {
      fatherName: "T. Natesan",
      fatherOccupation: "Superintending Engineer, PWD Tamil Nadu",
      motherName: "Shenbagam Natesan",
      motherOccupation: "Government School Headmistress",
      siblings: "1 Elder Brother (M.S. USA)",
      familyType: "Nuclear Family",
      familyValues: "Moderate & Cultured",
      familyStatus: "Upper Middle Class",
    },
    
    partnerPreferences: {
      ageMin: 27,
      ageMax: 31,
      heightMin: "5' 7\"",
      maritalStatus: "Never Married",
      education: "B.Arch / B.Tech / M.Tech / MBA / MS",
      profession: "Architect / IT / Entrepreneur / Engineer",
      location: "Chennai / Bengaluru / USA",
      castePreference: "Mudaliar / Saiva Pillai / Open",
      horoscopeMatchReq: "Preferred"
    },
    
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600",
    gallery: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600"
    ],
    about: "Creative architect passionate about sustainable home designs and eco-friendly spaces. Loves sketching, pottery, filter tea, and weekend getaway drives to Pondicherry.",
    phone: "+91 97909 34567",
    email: "divya.natesan.arch@gmail.com",
    verified: true,
    joinedDate: "2026-02-18"
  },
  {
    id: "JM202600106",
    name: "Surya Prakash",
    gender: "Male",
    age: 30,
    dob: "1996-06-11",
    birthTime: "02:15 PM",
    birthPlace: "Chennai",
    height: "6' 0\" (183 cm)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Vanniyar",
    subcaste: "Padayachi",
    gothram: "Jambumaharishi",
    education: "M.Tech Cyber Security",
    institution: "IIT Madras",
    profession: "Lead Cyber Security Specialist",
    company: "Standard Chartered Bank",
    annualIncome: "₹26,000,000 / annum",
    city: "Chennai",
    nativeTown: "Tindivanam",
    state: "Tamil Nadu",
    country: "India",
    
    rasi: "Mesham (Aries)",
    nakshatra: "Ashwini",
    padam: "4",
    lagnam: "Thulaam (Libra)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Thulaam", "Lagnam"],
      2: ["Vrichigam"],
      3: ["Dhanusu", "Guru"],
      4: ["Makaram", "Rahu"],
      5: ["Kumbam"],
      6: ["Meenam"],
      7: ["Mesham", "Chandran", "Sevvai"],
      8: ["Rishabam", "Sukran"],
      9: ["Mithunam", "Suriyan", "Budhan"],
      10: ["Katakamd", "Kethu"],
      11: ["Simmam"],
      12: ["Kanni", "Sani"]
    },
    
    family: {
      fatherName: "P. Jayaprakash",
      fatherOccupation: "Assistant Commissioner of Police (Retd)",
      motherName: "Kasturi Jayaprakash",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Sister (B.E., Married)",
      familyType: "Nuclear Family",
      familyValues: "Modern & Values Oriented",
      familyStatus: "Upper Middle Class",
    },
    
    partnerPreferences: {
      ageMin: 24,
      ageMax: 29,
      heightMin: "5' 4\"",
      maritalStatus: "Never Married",
      education: "Engineering / Medical / Degree",
      profession: "IT / Banking / Teaching / Healthcare",
      location: "Chennai / Nearby TN Cities",
      castePreference: "Vanniyar / Open",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=600",
    gallery: [
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=600"
    ],
    about: "IIT Madras alumnus with strong moral values. Passionate about cybersecurity, ethical hacking, marathon running, and visiting ancient temples across Tamil Nadu.",
    phone: "+91 98840 45678",
    email: "surya.iitm.cyber@gmail.com",
    verified: true,
    joinedDate: "2026-02-05"
  }
];

export const CASTE_LIST = [
  "All Communities",
  "Iyer",
  "Iyengar",
  "Gounder",
  "Pillai",
  "Mudaliar",
  "Chettiar",
  "Vanniyar",
  "Thevar / Kallar",
  "Nadar",
  "Naidu",
  "Viswakarma",
  "Reddy",
  "Adidravidar",
  "Inter-caste / Open"
];

export const CITIES_LIST = [
  "All Cities",
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Trichy",
  "Salem",
  "Tirunelveli",
  "Erode",
  "Vellore",
  "Thanjavur",
  "Kanchipuram",
  "Bengaluru",
  "NRI - USA",
  "NRI - Singapore / Malaysia",
  "NRI - UAE / Gulf"
];
