// Authentic Profiles Data from Attached Chennai Jothi Matrimony Registration Forms

export const MOCK_PROFILES = [
  {
    id: "JM202600709",
    regNo: "709",
    name: "R. Samantha",
    gender: "Female",
    age: 26,
    dob: "1999-08-21",
    birthTime: "08:30 AM",
    birthPlace: "Chennai",
    siblingPosition: "2nd Child",
    height: "5' 5\" (165 cm)",
    complexion: "Fair (Sivappu)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Vanniyar",
    subcaste: "Vanniyakula Kshatriyar",
    gothram: "Shiva",
    education: "M.A., M.Phil",
    institution: "University of Madras",
    profession: "Assistant Professor (Uthavi Peraasiriyar)",
    company: "Govt Arts & Science College",
    annualIncome: "₹1,500,000 / annum",
    monthlyIncome: "₹1,00,000 + Rent / month",
    city: "Chennai",
    nativeTown: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    address: "No. 12, NNo 6 Dubai Sany Sq, Nungambakkam, Chennai - 600034",
    
    // Horoscope details
    rasi: "Dhanusu (Sagittarius)",
    nakshatra: "Moolam",
    padam: "1",
    lagnam: "Makaram (Capricorn)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Mesham"],
      2: ["Rishabam", "Suriyan", "Sevvai"],
      3: ["Mithunam"],
      4: ["Katakam"],
      5: ["Simmam"],
      6: ["Kanni", "Rahu"],
      7: ["Thulaam"],
      8: ["Vrichigam", "Chandran"],
      9: ["Dhanusu", "Lagnam", "Guru"],
      10: ["Makaram"],
      11: ["Kumbam", "Kethu"],
      12: ["Meenam"]
    },
    
    // Family Details
    family: {
      fatherName: "Dr. D. Rajkumar",
      fatherOccupation: "Southern Railway (Retired) [S.RLY RTD]",
      motherName: "Thirumathi R. Chitra",
      motherOccupation: "Homemaker",
      siblings: "1 Elder Sister (Married)",
      familyType: "Nuclear Family",
      familyValues: "Traditional & Modern",
      familyStatus: "Upper Middle Class",
      houseProperty: "Own House (Sonda Veedu)"
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 27,
      ageMax: 33,
      heightMin: "5' 8\"",
      maritalStatus: "Never Married",
      education: "Master's / B.E. / M.E. / Ph.D / Govt Employee",
      profession: "Govt Officer / Professor / IT Professional",
      location: "Chennai / Madurai / Trichy",
      castePreference: "Vanniyar / Govt / Private",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "/profiles/709.jpg",
    gallery: [
      "/profiles/709.jpg"
    ],
    about: "Assistant Professor with M.A., M.Phil qualifications residing in Nungambakkam, Chennai. Father retired from Southern Railways. Belongs to a highly respected Vanniyar family. Seeking a well-educated groom in Chennai, Madurai, or Trichy.",
    phone: "+91 90437 73977",
    email: "samantha.r.jm@gmail.com",
    verified: true,
    joinedDate: "2026-03-01"
  },
  {
    id: "JM202600710",
    regNo: "710",
    name: "R. Manikandan",
    gender: "Male",
    age: 32,
    dob: "1993-12-24",
    birthTime: "02:00 AM",
    birthPlace: "Dharmapuri",
    siblingPosition: "Elder Son",
    height: "5' 8\" (173 cm)",
    complexion: "Wheatish (Maaniram)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Vanniyar",
    subcaste: "Vanniyakula Kshatriyar (MBC)",
    gothram: "Agni",
    education: "B.Sc Chemistry",
    institution: "Arts & Science College, Dharmapuri",
    profession: "Sales Manager",
    company: "Dr. Reddy's Laboratories (Hyderabad)",
    annualIncome: "₹1,200,000 / annum",
    monthlyIncome: "₹1,00,000 / month",
    city: "Dharmapuri",
    nativeTown: "Dharmapuri",
    state: "Tamil Nadu",
    country: "India",
    
    // Horoscope details
    rasi: "Kanni (Virgo)",
    nakshatra: "Chithirai",
    padam: "2",
    lagnam: "Thulaam (Libra)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Mesham"],
      2: ["Rishabam"],
      3: ["Mithunam"],
      4: ["Katakam"],
      5: ["Simmam"],
      6: ["Kanni", "Chandran"],
      7: ["Thulaam", "Lagnam"],
      8: ["Vrichigam"],
      9: ["Dhanusu", "Suriyan", "Budhan"],
      10: ["Makaram", "Sevvai", "Sukran"],
      11: ["Kumbam", "Sani"],
      12: ["Meenam", "Rahu"]
    },
    
    // Family Details
    family: {
      fatherName: "Thiru Ramajayam",
      fatherOccupation: "Agriculturist (Vivasayam)",
      motherName: "Thirumathi Kannaki",
      motherOccupation: "Agriculturist (Vivasayam)",
      siblings: "1 Younger Sister (Married)",
      familyType: "Traditional Family",
      familyValues: "Traditional",
      familyStatus: "Middle Class",
      houseProperty: "Own House & 1 Acre Agricultural Land"
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 23,
      ageMax: 28,
      heightMin: "5' 2\"",
      maritalStatus: "Never Married",
      education: "Graduate / Degree / Diploma",
      profession: "Any / Homemaker / Teacher / IT",
      location: "Dharmapuri / Salem / Krishnagiri / TN",
      castePreference: "Vanniyakula Kshatriyar",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "/profiles/710.jpg",
    gallery: [
      "/profiles/710.jpg"
    ],
    about: "B.Sc Chemistry graduate working as Sales Manager at Dr. Reddy's Laboratories (HYD). Native of Dharmapuri with own house and 1 acre agricultural land. Looking for a traditional bride from MBC Vanniyakula Kshatriyar community.",
    phone: "+91 94449 34527",
    email: "manikandan.r.jm@gmail.com",
    verified: true,
    joinedDate: "2026-03-05"
  },
  {
    id: "JM202600711",
    regNo: "711",
    name: "A.R. Sakthivel Aathithya",
    gender: "Male",
    age: 31,
    dob: "1994-05-05",
    birthTime: "07:42 AM",
    birthPlace: "Chennai",
    siblingPosition: "1st Child (Elder Son)",
    height: "5' 10\" (178 cm)",
    complexion: "Wheatish",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Mudaliar",
    subcaste: "Arcot Mudaliar",
    gothram: "Shiva",
    education: "B.Tech Mechatronics",
    institution: "SRM Institute of Science and Technology",
    profession: "Entrepreneur - Green Energy",
    company: "Self-Employed / Business Owner",
    annualIncome: "₹9,360,000 / annum",
    monthlyIncome: "₹7,80,000 / month",
    city: "Chennai",
    nativeTown: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    
    // Horoscope details
    rasi: "Meenam (Pisces)",
    nakshatra: "Revathi",
    padam: "4",
    lagnam: "Rishabam (Taurus)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Mesham", "Suriyan", "Sevvai"],
      2: ["Rishabam", "Lagnam"],
      3: ["Mithunam", "Guru", "Kethu"],
      4: ["Katakam"],
      5: ["Simmam"],
      6: ["Kanni", "Sani"],
      7: ["Thulaam"],
      8: ["Vrichigam"],
      9: ["Dhanusu", "Rahu"],
      10: ["Makaram"],
      11: ["Kumbam"],
      12: ["Meenam", "Chandran"]
    },
    
    // Family Details
    family: {
      fatherName: "Thiru A.T. Ramesh B.E.",
      fatherOccupation: "Senior Consultant, TCS (Retired)",
      motherName: "Thirumathi J. Mahalakshmi B.Sc",
      motherOccupation: "School Teacher",
      siblings: "1 Younger Sister (Unmarried)",
      familyType: "Nuclear Family",
      familyValues: "Modern & Traditional",
      familyStatus: "Affluent / Wealthy",
      houseProperty: "3 Independent Houses in Chennai"
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 23,
      ageMax: 28,
      heightMin: "5' 3\"",
      maritalStatus: "Never Married",
      education: "Graduate & Working / B.E. / B.Tech / MBA",
      profession: "Corporate / IT / Healthcare / Entrepreneur",
      location: "Chennai / Nearby Cities",
      castePreference: "Open to All Communities",
      horoscopeMatchReq: "Preferred"
    },
    
    photo: "/profiles/711.jpg",
    gallery: [
      "/profiles/711.jpg"
    ],
    about: "Green Energy Entrepreneur based in Chennai with B.Tech in Mechatronics. Father is a retired Senior Consultant from TCS (B.E.) and mother is a B.Sc School Teacher. Family owns 3 houses in Chennai. Looking for an educated, working bride.",
    phone: "+91 90437 73977",
    email: "sakthivel.aathithya.jm@gmail.com",
    verified: true,
    joinedDate: "2026-03-10"
  },
  {
    id: "JM202600777",
    regNo: "777",
    name: "J. Sowmik Siva",
    gender: "Male",
    age: 27,
    dob: "1999-02-17",
    birthTime: "07:15 AM",
    birthPlace: "Kattumannarkoil, Cuddalore",
    siblingPosition: "2nd Child",
    height: "6' 1\" (185 cm)",
    complexion: "Fair (Sivappu)",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Vanniyar",
    subcaste: "Vanniyar Kula Kshatriya",
    gothram: "Kashyapa",
    education: "B.E. Computer Science",
    institution: "SSN College of Engineering, Chennai",
    profession: "Senior Software Engineer",
    company: "Solaris Tech, Chennai",
    annualIncome: "₹900,000 / annum",
    monthlyIncome: "₹75,000 / month",
    city: "Chennai",
    nativeTown: "Kattumannarkoil, Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    
    // Horoscope details
    rasi: "Kumbam (Aquarius)",
    nakshatra: "Sadayam",
    padam: "2",
    lagnam: "Kumbam (Aquarius)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Kumbam", "Lagnam", "Chandran", "Suriyan"],
      2: ["Meenam", "Budhan"],
      3: ["Mesham"],
      4: ["Rishabam", "Rahu"],
      5: ["Mithunam"],
      6: ["Katakam"],
      7: ["Simmam"],
      8: ["Kanni"],
      9: ["Thulaam"],
      10: ["Vrichigam", "Kethu"],
      11: ["Dhanusu", "Guru"],
      12: ["Makaram", "Sani", "Sevvai"]
    },
    
    // Family Details
    family: {
      fatherName: "Thiru S. Jagadeesan M.S. (Soft Eng)",
      fatherOccupation: "Businessman",
      motherName: "Thirumathi J. Shobana",
      motherOccupation: "Homemaker",
      siblings: "Nil",
      familyType: "Nuclear Family",
      familyValues: "Traditional & Modern",
      familyStatus: "Upper Middle Class",
      houseProperty: "Own House & 4.5 Ground Property"
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 22,
      ageMax: 26,
      heightMin: "5' 4\"",
      maritalStatus: "Never Married",
      education: "B.E / B.Tech / MCA / M.Sc",
      profession: "Software Engineer / IT Professional working in Chennai",
      location: "Chennai / Cuddalore",
      castePreference: "Vanniyar",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "/profiles/777.jpg",
    gallery: [
      "/profiles/777.jpg"
    ],
    about: "Tall (6'1\") Senior Software Engineer working at Solaris Tech, Chennai earning ₹9L PA. Native of Kattumannarkoil, Cuddalore. Father holds M.S. in Software Engineering & runs business. Family owns 4.5 ground property. Seeking IT working bride in Chennai.",
    phone: "+91 94449 34527",
    email: "sowmiksiva.j.jm@gmail.com",
    verified: true,
    joinedDate: "2026-03-12"
  },
  {
    id: "JM202600712",
    regNo: "712",
    name: "Dinesh Rao",
    gender: "Male",
    age: 38,
    dob: "1987-09-27",
    birthTime: "02:30 AM",
    birthPlace: "Chennai",
    siblingPosition: "Middle Son",
    height: "5' 6\" (168 cm)",
    complexion: "Wheatish",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Maruthuvar",
    subcaste: "Yadav / Maruthuvar",
    gothram: "Vishwamitra",
    education: "10th Standard",
    institution: "Govt Higher Sec School, Chennai",
    profession: "Salon Owner (Classic Saloon)",
    company: "Self-Employed (Own Shop)",
    annualIncome: "₹720,000 / annum",
    monthlyIncome: "₹60,000 / month",
    city: "Chennai",
    nativeTown: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    address: "#26/A.V.M. Avenue 2nd Street, Virugambakkam, Chennai - 600092",
    
    // Horoscope details
    rasi: "Thulaam (Libra)",
    nakshatra: "Visakam",
    padam: "3",
    lagnam: "Katakam (Cancer)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Mesham"],
      2: ["Rishabam"],
      3: ["Mithunam"],
      4: ["Katakam", "Lagnam"],
      5: ["Simmam"],
      6: ["Kanni", "Suriyan", "Budhan"],
      7: ["Thulaam", "Chandran", "Sukran"],
      8: ["Vrichigam", "Sevvai"],
      9: ["Dhanusu"],
      10: ["Makaram", "Sani"],
      11: ["Kumbam", "Rahu"],
      12: ["Meenam", "Guru", "Kethu"]
    },
    
    // Family Details
    family: {
      fatherName: "Thiru Dhamodharan Rao",
      fatherOccupation: "Electrician",
      motherName: "Thirumathi Ganga Bai",
      motherOccupation: "Homemaker",
      siblings: "2 Brothers (1 Elder, 1 Younger - Both Married)",
      familyType: "Close-knit Family",
      familyValues: "Traditional",
      familyStatus: "Middle Class",
      houseProperty: "Own House in Virugambakkam, Chennai"
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 28,
      ageMax: 35,
      heightMin: "5' 0\"",
      maritalStatus: "Never Married",
      education: "Any / 10th / 12th / Graduate",
      profession: "Homemaker or Working",
      location: "Chennai",
      castePreference: "Maruthuvar / Yadav / Open",
      horoscopeMatchReq: "Preferred"
    },
    
    photo: "/profiles/712.jpg",
    gallery: [
      "/profiles/712.jpg"
    ],
    about: "Hardworking business owner running Classic Saloon in Virugambakkam, Chennai. Earning ₹60,000/month with own house in Virugambakkam. Native of Chennai. Looking for an understanding bride for a happy marital life.",
    phone: "+91 90437 73977",
    email: "dineshrao.jm@gmail.com",
    verified: true,
    joinedDate: "2026-03-15"
  },
  {
    id: "JM202600713",
    regNo: "713",
    name: "M. Kavimani",
    gender: "Male",
    age: 29,
    dob: "1997-01-21",
    birthTime: "11:04 PM",
    birthPlace: "Arakkonam",
    siblingPosition: "Elder Son",
    height: "5' 2\" (157 cm)",
    complexion: "Fair",
    maritalStatus: "Never Married",
    motherTongue: "Tamil",
    religion: "Hindu",
    caste: "Vanniyar",
    subcaste: "Vanniyar Kula Kshatriya",
    gothram: "Shiva",
    education: "Hotel Management",
    institution: "Catering Institute, Arakkonam",
    profession: "Hotel Owner & Manager",
    company: "Own Hotel & Food Organization",
    annualIncome: "₹480,000 / annum",
    monthlyIncome: "₹40,000 / month",
    city: "Kanchipuram",
    nativeTown: "Arakkonam / Walajabad",
    state: "Tamil Nadu",
    country: "India",
    address: "Arakkonam / Walajabad - 631605, Kancheepuram Dist.",
    
    // Horoscope details
    rasi: "Mithunam (Gemini)",
    nakshatra: "Thiruvathirai",
    padam: "2",
    lagnam: "Kanni (Virgo)",
    chevvaiDosham: "No",
    horoscopeAvailable: true,
    rasiChart: {
      1: ["Mesham"],
      2: ["Rishabam"],
      3: ["Mithunam", "Chandran", "Rahu"],
      4: ["Katakam"],
      5: ["Simmam"],
      6: ["Kanni", "Lagnam"],
      7: ["Thulaam"],
      8: ["Vrichigam"],
      9: ["Dhanusu", "Suriyan", "Budhan"],
      10: ["Makaram", "Sani", "Sukran"],
      11: ["Kumbam"],
      12: ["Meenam", "Guru", "Kethu"]
    },
    
    // Family Details
    family: {
      fatherName: "Thiru J. Madhavan",
      fatherOccupation: "Cook / Own Hotel (Ex-Railway)",
      motherName: "Thirumathi M. Pasupathiammal",
      motherOccupation: "Homemaker",
      siblings: "1 Younger Brother, 1 Younger Sister (Both Unmarried)",
      familyType: "Traditional Family",
      familyValues: "Traditional",
      familyStatus: "Middle Class",
      houseProperty: "Own House in Walajabad / Arakkonam"
    },
    
    // Partner Expectations
    partnerPreferences: {
      ageMin: 21,
      ageMax: 26,
      heightMin: "4' 10\"",
      maritalStatus: "Never Married",
      education: "+2 / Degree / Non-Engineering",
      profession: "Homemaker / Any",
      location: "Arakkonam / Kanchipuram / Chennai",
      castePreference: "Vanniyar Only",
      horoscopeMatchReq: "Mandatory"
    },
    
    photo: "/profiles/713.jpg",
    gallery: [
      "/profiles/713.jpg"
    ],
    about: "Entrepreneur running own Hotel & Catering business in Walajabad/Arakkonam. Father ex-railway chef running family catering business. Own house in Walajabad. Seeking a simple, cultured bride from Vanniyar community (+2 / Degree non-engg).",
    phone: "+91 94449 34527",
    email: "kavimani.m.jm@gmail.com",
    verified: true,
    joinedDate: "2026-03-18"
  }
];

export const CASTE_LIST = [
  "All Communities",
  "Vanniyar",
  "Mudaliar",
  "Gounder",
  "Pillai",
  "Chettiar",
  "Iyer",
  "Iyengar",
  "Nadar",
  "Thevar / Kallar / Maravar",
  "Naidu",
  "Maruthuvar",
  "Viswakarma / Achari",
  "Yadav / Konar",
  "Reddy",
  "Adi Dravidar",
  "Devendra Kula Vellalar",
  "Arunthathiyar",
  "Muthuraja / Muttaraiyar",
  "Parkavakulam (Udayar / Moopanar)",
  "Sourashtra",
  "Sengunthar",
  "Veera Saivam",
  "Meenavar / Sembadavar",
  "Devanga",
  "Boyar",
  "Badaga",
  "Kurumba",
  "Velar / Kuyavar",
  "Vannan / Rajaka",
  "Saliyar / Padmasaliyar",
  "Christian Matrimony",
  "Muslim Matrimony",
  "Inter-caste / Open to All"
];

export const SUBCASTE_MAP = {
  "Vanniyar": ["Vanniyakula Kshatriyar", "Padayachi", "Vanniya Gounder", "Vanniya Naicker", "Palli / Arasu"],
  "Mudaliar": ["Arcot Mudaliar", "Thondaimandala Saiva Mudaliar", "Sengunthar Mudaliar", "Agamudayar Mudaliar", "Vellala Mudaliar", "Isai Vellalar"],
  "Gounder": ["Kongu Vellalar Gounder", "Vattuva Gounder", "Nattu Gounder", "Kurumba Gounder", "Urali Gounder"],
  "Pillai": ["Saiva Pillai", "Tirunelveli Saiva Pillai", "Karkarthar Pillai", "Sozhia Vellalar", "Veerakodi Vellalar", "Illathu Pillai", "Kodikkal Pillai"],
  "Chettiar": ["Nattukottai Nagarathar", "Devanga Chettiar", "Beri Chettiar", "Komati / Arya Vysya", "Vania Chettiar", "Elur Chettiar", "Vallanattu Chettiar"],
  "Iyer": ["Vadama", "Brahacharanam", "Ashtasahasram", "Vathima", "Sholiyar", "Gurukkal / Dikshitar"],
  "Iyengar": ["Vadakalai", "Thenkalai"],
  "Nadar": ["Nadar (Southern)", "Karukku Mattai Nadar", "Mara Nadar", "Gramani Nadar"],
  "Thevar / Kallar / Maravar": ["Pramalai Kallar", "Ambalakarar", "Esanattu Kallar", "Kondayam Kottai Maravar", "Appanad Maravar", "Agamudayar (Servai)"],
  "Naidu": ["Kamma Naidu", "Kapu Naidu", "Balija Naidu", "Gavara Naidu", "Velama Naidu", "Kambalathar Naidu"],
  "Maruthuvar": ["Maruthuvar", "Vaidhyar", "Navithar", "Mangala / Pandithar"],
  "Viswakarma / Achari": ["Gold Smith (Tattan)", "Carpenter (Thachchan)", "Blacksmith (Kollar)", "Sculptor (Kalthachchan)", "Brass Smith (Kannan)"],
  "Yadav / Konar": ["Vaduga Yadav", "Erumai Yadav", "Tamil Konar", "Aayar / Idaiyar"],
  "Reddy": ["Konda Reddy", "Pokanati Reddy", "Desoor Reddy", "Velanati Reddy", "Ganjam Reddy"],
  "Adi Dravidar": ["Adi Dravidar", "Paraiyar", "Sambavar"],
  "Devendra Kula Vellalar": ["Kudumbar", "Pannadi", "Kalaadi", "Devendrar"],
  "Arunthathiyar": ["Arunthathiyar", "Chakkiliyar", "Madiga"],
  "Muthuraja / Muttaraiyar": ["Ambalakarar", "Muttaraiyar", "Muthuraja"],
  "Parkavakulam (Udayar / Moopanar)": ["Nainar", "Moopanar", "Malayaman Udayar", "Nathaman Udayar"],
  "Sourashtra": ["Sourashtra Brahmin", "Sourashtra Vaishnava"],
  "Sengunthar": ["Sengunthar Kaikolar"],
  "Veera Saivam": ["Jangam", "Veera Saivam"],
  "Meenavar / Sembadavar": ["Parvatha Rajakulam", "Sembadavar", "Pattinavar"],
  "Devanga": ["Devanga Chettiar", "Devanga Weaver"],
  "Christian Matrimony": ["Roman Catholic", "CSI", "Pentecostal", "Syrian Christian", "Protestant"],
  "Muslim Matrimony": ["Rowther", "Lebbai", "Marakayar", "Tamil Muslim", "Deccani"],
  "Inter-caste / Open to All": ["Inter-caste", "Caste No Bar", "Open to All"]
};

export const ALL_SUBCASTES = Object.values(SUBCASTE_MAP).flat();


export const CITIES_LIST = [
  "All Cities",
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Trichy",
  "Salem",
  "Tirunelveli",
  "Erode",
  "Vellore",
  "Thanjavur",
  "Kanchipuram",
  "Bengaluru",
  "NRI - USA",
  "NRI - Singapore / Malaysia",
  "NRI - UAE / Gulf"
];

export const HEIGHT_LIST = [
  "3' 6\" (107 cm)",
  "3' 7\" (109 cm)",
  "3' 8\" (112 cm)",
  "3' 9\" (114 cm)",
  "3' 10\" (117 cm)",
  "3' 11\" (119 cm)",
  "4' 0\" (122 cm)",
  "4' 1\" (124 cm)",
  "4' 2\" (127 cm)",
  "4' 3\" (130 cm)",
  "4' 4\" (132 cm)",
  "4' 5\" (135 cm)",
  "4' 6\" (137 cm)",
  "4' 7\" (140 cm)",
  "4' 8\" (142 cm)",
  "4' 9\" (145 cm)",
  "4' 10\" (147 cm)",
  "4' 11\" (150 cm)",
  "5' 0\" (152 cm)",
  "5' 1\" (155 cm)",
  "5' 2\" (157 cm)",
  "5' 3\" (160 cm)",
  "5' 4\" (163 cm)",
  "5' 5\" (165 cm)",
  "5' 6\" (168 cm)",
  "5' 7\" (170 cm)",
  "5' 8\" (173 cm)",
  "5' 9\" (175 cm)",
  "5' 10\" (178 cm)",
  "5' 11\" (180 cm)",
  "6' 0\" (183 cm)",
  "6' 1\" (185 cm)",
  "6' 2\" (188 cm)",
  "6' 3\" (191 cm)",
  "6' 4\" (193 cm)",
  "6' 5\" (196 cm)",
  "6' 6\" (198 cm)",
  "6' 7\" (201 cm)",
  "6' 8\" (203 cm)",
  "6' 9\" (206 cm)",
  "6' 10\" (208 cm)",
  "6' 11\" (211 cm)",
  "7' 0\" (213 cm)"
];

export const RELIGION_LIST = [
  "All Religions",
  "Hindu",
  "Muslim",
  "Christian",
  "Jain",
  "Sikh",
  "Buddhist",
  "Parsi / Zoroastrian",
  "Inter-religion / Open to All"
];


